### POST New User 
POST http://localhost:3000/createPlayer 
Content-Type: application/json; charset=utf-8

{
    "name": "John Doe","jersey":1,"position":"QB","team":"DAL"
}


###GET ALL
GET http://localhost:3000/getPlayers

###GET by name
GET http://localhost:3000/getPlayers?&q=todd